### ISSUE TITLE
'C:\e:' no such file or directory

### ISSUE THREAD

**Issue by llgcode** [moshfeu/vscode-compare-folders#10]
When first try the extension I have this error
```
[2020-01-06 09:59:18.765] [renderer1] [error] ENOENT: no such file or directory, lstat 'C:\e:': Error: ENOENT: no such file or directory, lstat 'C:\e:'
	at Object.realpathSync (fs.js:1470:7)
	at Object.fs.realpathSync (electron/js2c/asar.js:300:40)
	at Object.fs.realpathSync (electron/js2c/asar.js:300:40)
	at Object.compareSync (c:\Users\xxx\.vscode\extensions\moshfeu.compare-folders-0.4.0\node_modules\dir-compare\index.js:14:66)
	at compare (c:\Users\xxx\.vscode\extensions\moshfeu.compare-folders-0.4.0\out\services\comparer.js:41:31)
	at Object.<anonymous> (c:\Users\xxx\.vscode\extensions\moshfeu.compare-folders-0.4.0\out\services\comparer.js:21:16)
	at Generator.next (<anonymous>)
	at fulfilled (c:\Users\xxx\.vscode\extensions\moshfeu.compare-folders-0.4.0\out\services\comparer.js:5:58)
	at o (c:\Users\xxx\.vscode\extensions\vscjava.vscode-java-test-0.22.0\dist\extension.bundle.js:9:136323)
	at c:\Users\xxx\.vscode\extensions\vscjava.vscode-java-test-0.22.0\dist\extension.bundle.js:9:136820
```

**Comment by moshfeu** [comment]
Thank you!
Can you describe the steps you did before you got the error?
Thus path is indeed looking odd to me. Is it shared folder (on your local network). Is it symlink to another folder?
Can you send a screenshot with the error?
Thanks!

**Comment by llgcode** [comment]
I found this trace in log output.
I've just open a folder from "differences" panel (Click to select a folder) and select one on my drive that is located in E: but nothing happen so I've open output panel and saw this trace so I supposed that trace is the cause of the error.

**Comment by moshfeu** [comment]
Thank you!
I think that I able to reproduce the issue on Windows (10).
Which OS are you using?

**Comment by llgcode** [comment]
yes win10,
I've just the root cause of the problem I've download your extension source code.

In the constructor of the CompareFoldersProvider class, you have to replace
```ts
workspace.workspaceFolders[0].uri.path
```

```ts
workspace.workspaceFolders[0].uri.fsPath
```

**Comment by moshfeu** [comment]
Thank you!
Just found that too :)

Want to create a PR? 🙏

**Comment by llgcode** [comment]
I compare 2 big folders, the comparison take time, I have some suggestions:
- can we exclude files or folders (with pattern) from the comparison
- so It would be great to have a progress bar, in my extension I use this `window.withProgress`, so we can wait until the comparison is done
- I have a lot of differences between 2 folders can we have a tree view that display folders hierarchically, so it looks familiar.

Yes I can create a PR. I prepare it now

**Comment by moshfeu** [comment]
Thank you!

> can we exclude files or folders (with pattern) from the comparison

#3 

> so It would be great to have a progress bar, in my extension I use this window.withProgress, so we can wait until the comparison is done

Great feature

> I have a lot of differences between 2 folders can we have a tree view that display folders hierarchically, so it looks familiar.

Seems like it's somehow connected to that issue because on mac (it is displaying the folders hierarchically) - I guess that this what you mean

<img width="334" alt="Screen Shot 2020-01-06 at 15 50 13" src="https://user-images.githubusercontent.com/3723951/71821960-3f1b3300-309c-11ea-8fad-3bc2a3e5b161.png">
