### ISSUE TITLE
[error] compared path is not set

### ISSUE THREAD

**Issue by footya** [moshfeu/vscode-compare-folders#112]
**Original message**: Oops, something went wrong while comparing

**System Info**
Editor version: 1.73.1
Extension version: 0.20.1
OS: darwin 21.6.0

**Stack**
Error: compared path is not set
    at PathContext.get comparedPath [as comparedPath] (/Users/apple/.vscode/extensions/moshfeu.compare-folders-insider-0.22.1/out/context/path.js:19:19)
    at PathContext.getPaths (/Users/apple/.vscode/extensions/moshfeu.compare-folders-insider-0.22.1/out/context/path.js:32:37)
    at Object.<anonymous> (/Users/apple/.vscode/extensions/moshfeu.compare-folders-insider-0.22.1/out/services/comparer.js:115:67)
    at Generator.next (<anonymous>)
    at /Users/apple/.vscode/extensions/moshfeu.compare-folders-insider-0.22.1/out/services/comparer.js:27:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/apple/.vscode/extensions/moshfeu.compare-folders-insider-0.22.1/out/services/comparer.js:23:12)
    at Object.compareFolders (/Users/apple/.vscode/extensions/moshfeu.compare-folders-insider-0.22.1/out/services/comparer.js:109:12)
    at CompareFoldersProvider.<anonymous> (/Users/apple/.vscode/extensions/moshfeu.compare-folders-insider-0.22.1/out/providers/foldersCompareProvider.js:107:48)
    at Generator.next (<anonymous>)
    at /Users/apple/.vscode/extensions/moshfeu.compare-folders-insider-0.22.1/out/providers/foldersCompareProvider.js:27:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/apple/.vscode/extensions/moshfeu.compare-folders-insider-0.22.1/out/providers/foldersCompareProvider.js:23:12)
    at CompareFoldersProvider.refresh (/Users/apple/.vscode/extensions/moshfeu.compare-folders-insider-0.22.1/out/providers/foldersCompareProvider.js:105:30)
    at s._executeContributedCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:92:111375)
    at s.$executeContributedCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:92:112079)
    at l._doInvokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:102:13680)
    at l._invokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:102:13362)
    at l._receiveRequest (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:102:12132)
    at l._receiveOneMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:102:11033)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:102:8941
    at h.invoke (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:61:145)
    at v.deliver (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:61:2266)
    at g.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:61:1844)
    at r.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:70:16515)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:118:17104
    at h.invoke (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:61:145)
    at v.deliver (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:61:2266)
    at g.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:61:1844)
    at r.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:70:16515)
    at o._receiveMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:70:21327)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:70:18770
    at h.invoke (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:61:145)
    at v.deliver (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:61:2266)
    at g.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:61:1844)
    at g.acceptChunk (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:70:13346)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:70:12476
    at Socket.i (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:70:24594)
    at Socket.emit (node:events:526:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)

**Comment by moshfeu** [comment]
Thank you for the issue 🙏 

Can you describe what are the steps you did before you got this error?
