### ISSUE TITLE
[error] Maximum call stack size exceeded

### ISSUE THREAD

**Issue by legomanzeal** [moshfeu/vscode-compare-folders#134]
**Original message**: Oops, something went wrong while comparing

**System Info**
Editor version: 1.84.2
Extension version: 0.20.1
OS: darwin 21.6.0

**Stack**
RangeError: Maximum call stack size exceeded
	at String.match (<anonymous>)
	at Object.readBufferedLines (/Users/riaanv/.vscode/extensions/moshfeu.compare-folders-insider-0.22.1/node_modules/dir-compare/build/src/fileCompareHandler/lines/lineReader/readBufferedLines.js:23:49)
	at /Users/riaanv/.vscode/extensions/moshfeu.compare-folders-insider-0.22.1/node_modules/dir-compare/build/src/fileCompareHandler/lines/compareAsync.js:72:36
	at Generator.next (<anonymous>)
	at fulfilled (/Users/riaanv/.vscode/extensions/moshfeu.compare-folders-insider-0.22.1/node_modules/dir-compare/build/src/fileCompareHandler/lines/compareAsync.js:5:58)

**Comment by moshfeu** [comment]
Thanks for reporting the issue

I see that you are using the insider version which is no longer in development.
Would you mind trying the [regular version](https://marketplace.visualstudio.com/items?itemName=moshfeu.compare-folders)?

If the issue keeps happening, can you tell me more about the folders you are trying to compare? Maybe have dependencies folders such as _node_modules_ with a lot of files that can be easily excluded from the comparison and will decrease dramatically the number of files?
