### ISSUE TITLE
[error] Maximum call stack size exceeded

### ISSUE THREAD

**Issue by legomanzeal** [moshfeu/vscode-compare-folders#141]
**Original message**: Oops, something went wrong while comparing

**System Info**
Editor version: 1.85.1
Extension version: 0.20.1
OS: darwin 21.6.0

**Stack**
RangeError: Maximum call stack size exceeded
	at String.match (<anonymous>)
	at Object.readBufferedLines (/Users/riaanv/.vscode/extensions/moshfeu.compare-folders-insider-0.22.1/node_modules/dir-compare/build/src/fileCompareHandler/lines/lineReader/readBufferedLines.js:23:49)
	at /Users/riaanv/.vscode/extensions/moshfeu.compare-folders-insider-0.22.1/node_modules/dir-compare/build/src/fileCompareHandler/lines/compareAsync.js:72:36
	at Generator.next (<anonymous>)
	at fulfilled (/Users/riaanv/.vscode/extensions/moshfeu.compare-folders-insider-0.22.1/node_modules/dir-compare/build/src/fileCompareHandler/lines/compareAsync.js:5:58)

**Comment by moshfeu** [comment]
Hi @legomanzeal
Thanks for reporting the issue

Can you give more details about the folders you're trying to compare? 
How big they are? Are they regular folder or they or they have linked folders inside? Where are they located locally or remotely? Is the issue consistent in any pair folders comparing or only specific folders?

Any more details you can provide would help
