### ISSUE TITLE
[error] ENOENT: no such file or directory, stat 'D:\Users\DengWei.DWTHINKPAD\Desktop\github\freertos\e-2\Sample_DRV\Sensor'

### ISSUE THREAD

**Issue by Github-01309242** [moshfeu/vscode-compare-folders#168]
**Original message**: Failed to copy file

**System Info**
Editor version: 1.95.1
Extension version: 0.25.1
OS: win32 10.0.22631

**Stack**
Error: ENOENT: no such file or directory, stat 'D:\Users\DengWei.DWTHINKPAD\Desktop\github\freertos\e-2\Sample_DRV\Sensor'
	at statSync (node:fs:1668:25)
	at t.statSync (node:electron/js2c/node_init:2:5397)
	at Object.statSync (c:\Users\DengWei.DWTHINKPAD\.vscode\extensions\moshfeu.compare-folders-0.25.1\node_modules\graceful-fs\polyfills.js:318:34)
	at getStatsSync (c:\Users\DengWei.DWTHINKPAD\.vscode\extensions\moshfeu.compare-folders-0.25.1\node_modules\fs-extra\lib\util\stat.js:58:18)
	at Object.checkPathsSync (c:\Users\DengWei.DWTHINKPAD\.vscode\extensions\moshfeu.compare-folders-0.25.1\node_modules\fs-extra\lib\util\stat.js:90:33)
	at copySync (c:\Users\DengWei.DWTHINKPAD\.vscode\extensions\moshfeu.compare-folders-0.25.1\node_modules\fs-extra\lib\copy-sync\copy-sync.js:24:38)
	at CompareFoldersProvider.copyToFolder (c:\Users\DengWei.DWTHINKPAD\.vscode\extensions\moshfeu.compare-folders-0.25.1\out\providers\foldersCompareProvider.js:248:37)
	at CompareFoldersProvider.copyToCompared (c:\Users\DengWei.DWTHINKPAD\.vscode\extensions\moshfeu.compare-folders-0.25.1\out\providers\foldersCompareProvider.js:145:18)
	at Y0.h (file:///d:/Tool/Microsoft VS Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:114:32833)
	at Y0.$executeContributedCommand (file:///d:/Tool/Microsoft VS Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:114:33683)
	at py.S (file:///d:/Tool/Microsoft VS Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:31:113311)
	at py.Q (file:///d:/Tool/Microsoft VS Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:31:113091)
	at py.M (file:///d:/Tool/Microsoft VS Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:31:112180)
	at py.L (file:///d:/Tool/Microsoft VS Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:31:111418)
	at mh.value (file:///d:/Tool/Microsoft VS Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:31:110082)
	at D.B (file:///d:/Tool/Microsoft VS Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:29:746)
	at D.fire (file:///d:/Tool/Microsoft VS Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:29:964)
	at Vn.fire (file:///d:/Tool/Microsoft VS Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:31:9457)
	at mh.value (file:///d:/Tool/Microsoft VS Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:174:13279)
	at D.B (file:///d:/Tool/Microsoft VS Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:29:746)
	at D.fire (file:///d:/Tool/Microsoft VS Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:29:964)
	at Vn.fire (file:///d:/Tool/Microsoft VS Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:31:9457)
	at MessagePortMain.<anonymous> (file:///d:/Tool/Microsoft VS Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:174:11571)
	at MessagePortMain.emit (node:events:519:28)
	at MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:2:2949)

**Comment by lIllIIlI** [comment]
This version is horrible, it broke copy to my folder / take mine/theirs functionality 
Need to revert to older version to work

**Comment by moshfeu** [comment]
Sorry for that
The latest version supposed to fix this - https://github.com/moshfeu/vscode-compare-folders/releases/tag/v0.25.1
Clearly it's not the case for you

I don't the structure of your project of course but the path mentioned in the error makes sense (unlike the path people shared before the latest version). Can you tell me what's wrong with the path?

```
D:\Users\DengWei.DWTHINKPAD\Desktop\github\freertos\e-2\Sample_DRV\Senso
```

**Comment by moshfeu** [comment]
> This version is horrible, it broke copy to my folder / take mine/theirs functionality Need to revert to older version to work

@lIllIIlI are you using the latest version? Is there anything special with your workspace?

**Comment by azuravian** [comment]
I think I found a possible problem related to this.  I was having the same problem and the error was telling me that the file to be copied was on the C: drive when it was on the J: drive.

In Compare Folders settings, changing Diff View Title from name only to full path fixed the problem.  This should only effect the view, but it appears to be impact file system functions as well.

**Comment by moshfeu** [comment]
Thanks @azuravian , interesting point. You're right, it doesn't make sense 😅 Both of the problem and the solution
Seems like the problem is in win32. I'm trying to set it up in order to debug it
If anyone with win32 can take a look it would be great

**Comment by moshfeu** [comment]
Hi everyone

I reverted the code I modified in the last version to the one version before
Since I couldn't put my hands on a win32, I'd be happy if someone can test it on his/her machine

Thank you very much for reporting and for your collaboration 🙏 

[compare-folders-0.25.2.vsix.zip](https://github.com/user-attachments/files/17967194/compare-folders-0.25.2.vsix.zip)

**Comment by moshfeu** [comment]
Copilot and I created a fix version. Can you check please?

https://github.com/moshfeu/vscode-compare-folders/pull/213#issuecomment-3146288726
