### ISSUE TITLE
[error] ENOENT: no such file or directory, stat '\workspace\app2\app2\lib\mqtt\mqtt.dart'

### ISSUE THREAD

**Issue by lukalulu** [moshfeu/vscode-compare-folders#173]
**Original message**: Failed to copy file

**System Info**
Editor version: 1.87.0
Extension version: 0.25.1
OS: win32 10.0.19045

**Stack**
Error: ENOENT: no such file or directory, stat '\workspace\app2\app2\lib\mqtt\mqtt.dart'
    at statSync (node:fs:1692:3)
    at node:electron/js2c/node_init:2:4795
    at Object.n.statSync (c:\Users\Administrator\.vscode\extensions\esbenp.prettier-vscode-11.0.0\dist\extension.js:1:3435)
    at Object.statSync (c:\Users\Administrator\.vscode\extensions\moshfeu.compare-folders-0.25.1\node_modules\graceful-fs\polyfills.js:318:34)
    at getStatsSync (c:\Users\Administrator\.vscode\extensions\moshfeu.compare-folders-0.25.1\node_modules\fs-extra\lib\util\stat.js:58:18)
    at Object.checkPathsSync (c:\Users\Administrator\.vscode\extensions\moshfeu.compare-folders-0.25.1\node_modules\fs-extra\lib\util\stat.js:90:33)
    at copySync (c:\Users\Administrator\.vscode\extensions\moshfeu.compare-folders-0.25.1\node_modules\fs-extra\lib\copy-sync\copy-sync.js:24:38)
    at CompareFoldersProvider.copyToFolder (c:\Users\Administrator\.vscode\extensions\moshfeu.compare-folders-0.25.1\out\providers\foldersCompareProvider.js:248:37)
    at CompareFoldersProvider.takeMyFile (c:\Users\Administrator\.vscode\extensions\moshfeu.compare-folders-0.25.1\out\providers\foldersCompareProvider.js:167:18)
    at l.h (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:150:184954)
    at l.$executeContributedCommand (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:150:185814)
    at s.S (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:147:5519)
    at s.Q (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:147:5285)
    at s.M (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:147:4375)
    at s.L (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:147:3593)
    at w.value (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:147:2241)
    at n.y (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:80:1902)
    at n.fire (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:80:2119)
    at r.fire (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:105:14091)
    at w.value (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:173:8050)
    at n.y (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:80:1902)
    at n.fire (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:80:2119)
    at r.fire (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:105:14091)
    at MessagePortMain.<anonymous> (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:173:6330)
    at MessagePortMain.emit (node:events:514:28)
    at Object.emit (node:electron/js2c/utility_init:2:2285)

**Comment by moshfeu** [comment]
Hi @lukalulu, thank you for reporting
Seems like the extension has the issue in win32. I'm trying to set up win32 on my machine to debug it
If you are comfortable with the extension code and can help me to debug that would be great 🙏 
Thanks

There is a similar issue #168. Please follow it to get updates on this issue
