### ISSUE TITLE
[error] Maximum call stack size exceeded

### ISSUE THREAD

**Issue by davidbien** [moshfeu/vscode-compare-folders#174]
**Original message**: Oops, something went wrong while comparing

**System Info**
Editor version: 1.95.3
Extension version: 0.25.1
OS: darwin 24.0.0

**Stack**
RangeError: Maximum call stack size exceeded
    at String.match (<anonymous>)
    at readBufferedLines (/Users/davidbien/.vscode/extensions/moshfeu.compare-folders-0.25.1/node_modules/dir-compare/build/src/FileCompareHandler/lines/lineReader/readBufferedLines.js:23:49)
    at /Users/davidbien/.vscode/extensions/moshfeu.compare-folders-0.25.1/node_modules/dir-compare/build/src/FileCompareHandler/lines/lineBasedCompareAsync.js:69:58
    at Generator.next (<anonymous>)
    at fulfilled (/Users/davidbien/.vscode/extensions/moshfeu.compare-folders-0.25.1/node_modules/dir-compare/build/src/FileCompareHandler/lines/lineBasedCompareAsync.js:5:58)

**Comment by moshfeu** [comment]
Hi, thank you for reporting 

Can you tell if there are a special files in the folders? Links? Very large files?

**Comment by davidbien** [comment]
yeah there are a ton of directories and files etc - i use vcpkg and some very large libraries
you may want to consider a non-recursive algorithm - ie. a stack etc - i haven’t looked at your code but this is my guess

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by moshfeu** [comment]
I'm not familiar with _vcpkg_ but chatgpt told me that it stores the dependencies code in "vcpkg_installed".
Can you try to exclude it with [`excludeFilter`](https://github.com/moshfeu/vscode-compare-folders?tab=readme-ov-file#options-under-vscode-settings)?

**Comment by davidbien** [comment]
https://github.com/gliviu/dir-compare/blob/master/src/compareAsync.ts - you import compare from dir-compare, dir-compare seems to call compareAsync() impl method. Not only does compareAsync() recurse but it recurses asynchronously ( which seems kinda dumb because the caller called the initial call of compareAsync() asynchronously ). If it were me I would have an outer compareAsync wrapper that called an inner non-async recursive method, or even better instead of recursive, a method that accumulated the directories to compare in a stack or something like that.

**Comment by moshfeu** [comment]
Thanks for diving into this, it is really helpful and I appreciated.
I'd be happy to consult the author of dir-compare. Sorry for bothering you but before doing so, could you please refine your message to ensure it's as constructive as possible
