### ISSUE TITLE
[error] ENOENT: no such file or directory, stat 'C:\Jacob Stachowicz\Documents\Gaming\Minecraft\Prism Launcher\instances\GTNH GoG 2.7.0 Beta4 Backup\.minecraft\config\dsurround'

### ISSUE THREAD

**Issue by PlayfulPiano** [moshfeu/vscode-compare-folders#177]
**Original message**: Failed to copy file

**System Info**
Editor version: 1.95.2
Extension version: 0.25.1
OS: win32 10.0.19045

**Stack**
Error: ENOENT: no such file or directory, stat 'C:\Jacob Stachowicz\Documents\Gaming\Minecraft\Prism Launcher\instances\GTNH GoG 2.7.0 Beta4 Backup\.minecraft\config\dsurround'
    at statSync (node:fs:1668:25)
    at Object.t.statSync (node:electron/js2c/node_init:2:5397)
    at Object.statSync (c:\Users\jstac\.vscode\extensions\moshfeu.compare-folders-0.25.1\node_modules\graceful-fs\polyfills.js:318:34)
    at getStatsSync (c:\Users\jstac\.vscode\extensions\moshfeu.compare-folders-0.25.1\node_modules\fs-extra\lib\util\stat.js:58:18)
    at Object.checkPathsSync (c:\Users\jstac\.vscode\extensions\moshfeu.compare-folders-0.25.1\node_modules\fs-extra\lib\util\stat.js:90:33)
    at copySync (c:\Users\jstac\.vscode\extensions\moshfeu.compare-folders-0.25.1\node_modules\fs-extra\lib\copy-sync\copy-sync.js:24:38)
    at CompareFoldersProvider.copyToFolder (c:\Users\jstac\.vscode\extensions\moshfeu.compare-folders-0.25.1\out\providers\foldersCompareProvider.js:248:37)
    at CompareFoldersProvider.copyToMy (c:\Users\jstac\.vscode\extensions\moshfeu.compare-folders-0.25.1\out\providers\foldersCompareProvider.js:148:18)
    at Y0.h (file:///c:/Users/jstac/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:114:32833)
    at Y0.$executeContributedCommand (file:///c:/Users/jstac/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:114:33683)
    at py.S (file:///c:/Users/jstac/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:31:113311)
    at py.Q (file:///c:/Users/jstac/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:31:113091)
    at py.M (file:///c:/Users/jstac/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:31:112180)
    at py.L (file:///c:/Users/jstac/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:31:111418)
    at mh.value (file:///c:/Users/jstac/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:31:110082)
    at D.B (file:///c:/Users/jstac/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:29:746)
    at D.fire (file:///c:/Users/jstac/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:29:964)
    at Vn.fire (file:///c:/Users/jstac/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:31:9457)
    at mh.value (file:///c:/Users/jstac/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:174:13279)
    at D.B (file:///c:/Users/jstac/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:29:746)
    at D.fire (file:///c:/Users/jstac/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:29:964)
    at Vn.fire (file:///c:/Users/jstac/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:31:9457)
    at MessagePortMain.<anonymous> (file:///c:/Users/jstac/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:174:11571)
    at MessagePortMain.emit (node:events:519:28)
    at Object.MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:2:2949)

**Comment by moshfeu** [comment]
Hi @PlayfulPiano , thank you for reporting
Seems like the extension has the issue in win32 :\

There is a similar issue #168. Please follow it to get updates on this issue

**Comment by PlayfulPiano** [comment]
> Hi @PlayfulPiano , thank you for reporting
> Seems like the extension has the issue in win32 :\
> 
> There is a similar issue #168. Please follow it to get updates on this issue

Weird, bc my computer runs on x64

**Comment by PlayfulPiano** [comment]
Yeah and VSCode recognizes it as x64, not x32. Maybe that's why?
![image](https://github.com/user-attachments/assets/b0580dc8-8048-49ef-a5e0-56a54da54499)

**Comment by moshfeu** [comment]
My bad. [Seems like nodejs (and not just) calls it win32 even though it's 64](https://www.reddit.com/r/node/comments/7xx4u7/osplatform_includes_win32what_about_win64/)

Weird indeed given that I tried the extension on windows 64 and it worked

Anyway, can you try [this version](https://github.com/user-attachments/files/17967194/compare-folders-0.25.2.vsix.zip) and let me know if it fixed the bug? 🙏

**Comment by moshfeu** [comment]
Copilot and I created a fix version. Can you check please?

https://github.com/moshfeu/vscode-compare-folders/pull/213#issuecomment-3146288726
