### ISSUE TITLE
[error] Maximum call stack size exceeded

### ISSUE THREAD

**Issue by tolgakaratas** [moshfeu/vscode-compare-folders#178]
**Original message**: Oops, something went wrong while comparing

**System Info**
Editor version: 1.95.3
Extension version: 0.25.1
OS: darwin 24.1.0

**Stack**
RangeError: Maximum call stack size exceeded
	at RegExp.exec (<anonymous>)
	at /Users/tolgakaratas/.vscode/extensions/gruntfuggly.todo-tree-0.0.226/dist/extension.js:52:2722
	at e.exports (/Users/tolgakaratas/.vscode/extensions/gruntfuggly.todo-tree-0.0.226/dist/extension.js:52:3029)
	at [Symbol.match] (<anonymous>)
	at String.match (<anonymous>)
	at readBufferedLines (/Users/tolgakaratas/.vscode/extensions/moshfeu.compare-folders-0.25.1/node_modules/dir-compare/build/src/FileCompareHandler/lines/lineReader/readBufferedLines.js:23:49)
	at /Users/tolgakaratas/.vscode/extensions/moshfeu.compare-folders-0.25.1/node_modules/dir-compare/build/src/FileCompareHandler/lines/lineBasedCompareAsync.js:69:58
	at Generator.next (<anonymous>)
	at fulfilled (/Users/tolgakaratas/.vscode/extensions/moshfeu.compare-folders-0.25.1/node_modules/dir-compare/build/src/FileCompareHandler/lines/lineBasedCompareAsync.js:5:58)

**Comment by moshfeu** [comment]
Thanks @tolgakaratas 🙏 
It seems to occur in projects with a very deep hierarchy, but I'm not sure. Could you tell me about the level of hierarchy in your project?
