### ISSUE TITLE
[error] Maximum call stack size exceeded

### ISSUE THREAD

**Issue by Hadatko** [moshfeu/vscode-compare-folders#179]
**Original message**: Oops, something went wrong while comparing

**System Info**
Editor version: 1.95.2
Extension version: 0.25.1
OS: linux 6.11.0-9-generic

**Stack**
RangeError: Maximum call stack size exceeded
    at RegExp.exec (<anonymous>)
    at /home/acrios_cervenka/.vscode/extensions/gruntfuggly.todo-tree-0.0.226/dist/extension.js:52:2722
    at RegExp.e.exports (/home/acrios_cervenka/.vscode/extensions/gruntfuggly.todo-tree-0.0.226/dist/extension.js:52:3029)
    at [Symbol.match] (<anonymous>)
    at String.match (<anonymous>)
    at readBufferedLines (/home/acrios_cervenka/.vscode/extensions/moshfeu.compare-folders-0.25.1/node_modules/dir-compare/build/src/FileCompareHandler/lines/lineReader/readBufferedLines.js:23:49)
    at /home/acrios_cervenka/.vscode/extensions/moshfeu.compare-folders-0.25.1/node_modules/dir-compare/build/src/FileCompareHandler/lines/lineBasedCompareAsync.js:69:58
    at Generator.next (<anonymous>)
    at fulfilled (/home/acrios_cervenka/.vscode/extensions/moshfeu.compare-folders-0.25.1/node_modules/dir-compare/build/src/FileCompareHandler/lines/lineBasedCompareAsync.js:5:58)

**Comment by moshfeu** [comment]
Thanks for the report and sorry for the very long delay!
I'm having trouble reproducing this locally. The error occurs in the `dir-compare` library's line-matching logic, and from the stack traces, it appears to be specifically related to the **Todo Tree extension** intercepting RegExp operations.

**Could you help me confirm:**
1. Do you have the Todo Tree extension (`gruntfuggly.todo-tree`) installed?
2. Does the issue resolve if you temporarily disable Todo Tree or set `"compareFolders.compareContent": false`?

**Temporary workaround:**
Set `"compareFolders.compareContent": false` in your VS Code settings to bypass content comparison.

I'm adding defensive error handling to automatically detect this conflict and offer to retry without content comparison, which should be available in the next release.

**Comment by Hadatko** [comment]
Hello, i think we can close this one. I don't have issue now, i don't using that much and definitly i am not into reasearch 1year old report ;) Maybe next time.

P.S.: Happy to read that you are improving code based on this report ;)

P.s.2: Definitli i have Todo Tree now, and most likely i had also at that time.
