### ISSUE TITLE
[error] ENOENT: no such file or directory, stat 'd:\Jacob Stachowicz\Documents\Gaming\Minecraft\Prism Launcher\instances\GTNH GoG 2.7.0 RC2 Backup\.minecraft\config\d:\itemphysic.cfg'

### ISSUE THREAD

**Issue by PlayfulPiano** [moshfeu/vscode-compare-folders#180]
**Original message**: Failed to copy file

**System Info**
Editor version: 1.95.3
Extension version: 0.25.2
OS: win32 10.0.19045

**Stack**
Error: ENOENT: no such file or directory, stat 'd:\Jacob Stachowicz\Documents\Gaming\Minecraft\Prism Launcher\instances\GTNH GoG 2.7.0 RC2 Backup\.minecraft\config\d:\itemphysic.cfg'
    at statSync (node:fs:1668:25)
    at Object.t.statSync (node:electron/js2c/node_init:2:5397)
    at Object.statSync (c:\Users\jstac\.vscode\extensions\moshfeu.compare-folders-0.25.2\node_modules\graceful-fs\polyfills.js:318:34)
    at getStatsSync (c:\Users\jstac\.vscode\extensions\moshfeu.compare-folders-0.25.2\node_modules\fs-extra\lib\util\stat.js:58:18)
    at Object.checkPathsSync (c:\Users\jstac\.vscode\extensions\moshfeu.compare-folders-0.25.2\node_modules\fs-extra\lib\util\stat.js:90:33)
    at copySync (c:\Users\jstac\.vscode\extensions\moshfeu.compare-folders-0.25.2\node_modules\fs-extra\lib\copy-sync\copy-sync.js:24:38)
    at CompareFoldersProvider.copyToFolder (c:\Users\jstac\.vscode\extensions\moshfeu.compare-folders-0.25.2\out\providers\foldersCompareProvider.js:246:37)
    at CompareFoldersProvider.copyToCompared (c:\Users\jstac\.vscode\extensions\moshfeu.compare-folders-0.25.2\out\providers\foldersCompareProvider.js:140:18)
    at Y0.h (file:///c:/Users/jstac/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:114:32833)
    at Y0.$executeContributedCommand (file:///c:/Users/jstac/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:114:33683)
    at py.S (file:///c:/Users/jstac/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:31:113311)
    at py.Q (file:///c:/Users/jstac/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:31:113091)
    at py.M (file:///c:/Users/jstac/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:31:112180)
    at py.L (file:///c:/Users/jstac/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:31:111418)
    at mh.value (file:///c:/Users/jstac/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:31:110082)
    at D.B (file:///c:/Users/jstac/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:29:746)
    at D.fire (file:///c:/Users/jstac/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:29:964)
    at Vn.fire (file:///c:/Users/jstac/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:31:9457)
    at mh.value (file:///c:/Users/jstac/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:174:13300)
    at D.B (file:///c:/Users/jstac/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:29:746)
    at D.fire (file:///c:/Users/jstac/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:29:964)
    at Vn.fire (file:///c:/Users/jstac/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:31:9457)
    at MessagePortMain.<anonymous> (file:///c:/Users/jstac/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:174:11592)
    at MessagePortMain.emit (node:events:519:28)
    at Object.MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:2:2949)

**Comment by PlayfulPiano** [comment]
This is using the new version that was provided earlier, sorry it took a few days to use it. I was able to copy a few folders before this error popped up.

**Comment by moshfeu** [comment]
Copilot and I created a fix version. Can you check please?

https://github.com/moshfeu/vscode-compare-folders/pull/213#issuecomment-3146288726
