### ISSUE TITLE
[error] ENOENT: no such file or directory, stat 'C:\M\Projects\FadakBackoffice-NewVersion\src\@menu'

### ISSUE THREAD

**Issue by Majid-Ebrahimi** [moshfeu/vscode-compare-folders#181]
**Original message**: Failed to copy file

**System Info**
Editor version: 1.96.0
Extension version: 0.25.1
OS: win32 10.0.22000

**Stack**
Error: ENOENT: no such file or directory, stat 'C:\M\Projects\FadakBackoffice-NewVersion\src\@menu'
    at statSync (node:fs:1668:25)
    at Object.t.statSync (node:electron/js2c/node_init:2:5397)
    at Object.statSync (c:\Users\ebrahimi.m.FADAK\.vscode\extensions\moshfeu.compare-folders-0.25.1\node_modules\graceful-fs\polyfills.js:318:34)
    at getStatsSync (c:\Users\ebrahimi.m.FADAK\.vscode\extensions\moshfeu.compare-folders-0.25.1\node_modules\fs-extra\lib\util\stat.js:58:18)
    at Object.checkPathsSync (c:\Users\ebrahimi.m.FADAK\.vscode\extensions\moshfeu.compare-folders-0.25.1\node_modules\fs-extra\lib\util\stat.js:90:33)
    at copySync (c:\Users\ebrahimi.m.FADAK\.vscode\extensions\moshfeu.compare-folders-0.25.1\node_modules\fs-extra\lib\copy-sync\copy-sync.js:24:38)
    at CompareFoldersProvider.copyToFolder (c:\Users\ebrahimi.m.FADAK\.vscode\extensions\moshfeu.compare-folders-0.25.1\out\providers\foldersCompareProvider.js:248:37)
    at CompareFoldersProvider.copyToCompared (c:\Users\ebrahimi.m.FADAK\.vscode\extensions\moshfeu.compare-folders-0.25.1\out\providers\foldersCompareProvider.js:145:18)
    at cw.h (file:///c:/Users/ebrahimi.m.FADAK/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:115:32833)
    at cw.$executeContributedCommand (file:///c:/Users/ebrahimi.m.FADAK/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:115:33683)
    at Dy.S (file:///c:/Users/ebrahimi.m.FADAK/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:32:115275)
    at Dy.Q (file:///c:/Users/ebrahimi.m.FADAK/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:32:115055)
    at Dy.M (file:///c:/Users/ebrahimi.m.FADAK/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:32:114144)
    at Dy.L (file:///c:/Users/ebrahimi.m.FADAK/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:32:113382)
    at kh.value (file:///c:/Users/ebrahimi.m.FADAK/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:32:112046)
    at P.B (file:///c:/Users/ebrahimi.m.FADAK/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:30:746)
    at P.fire (file:///c:/Users/ebrahimi.m.FADAK/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:30:964)
    at Vn.fire (file:///c:/Users/ebrahimi.m.FADAK/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:32:9457)
    at kh.value (file:///c:/Users/ebrahimi.m.FADAK/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:175:13296)
    at P.B (file:///c:/Users/ebrahimi.m.FADAK/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:30:746)
    at P.fire (file:///c:/Users/ebrahimi.m.FADAK/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:30:964)
    at Vn.fire (file:///c:/Users/ebrahimi.m.FADAK/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:32:9457)
    at MessagePortMain.<anonymous> (file:///c:/Users/ebrahimi.m.FADAK/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:175:11588)
    at MessagePortMain.emit (node:events:518:28)
    at Object.MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:2:2949)

**Comment by moshfeu** [comment]
Thanks for reporting this and sorry for the delay.
Can you check if the issue occurs in version 0.24.3?
If not, I'll revert 0.25.x and figure out what's the root cause of this issue
Thanks

**Comment by moshfeu** [comment]
copilot and I created a fix version. Can you check please?

https://github.com/moshfeu/vscode-compare-folders/pull/213#issuecomment-3146288726
